apiVersion: dashboard.grafana.app/v2
kind: Dashboard
metadata:
  name: adpnjjh
spec:
  annotations:
    - kind: AnnotationQuery
      spec:
        builtIn: true
        enable: true
        hide: true
        iconColor: rgba(0, 211, 255, 1)
        name: Annotations & Alerts
        query:
          datasource:
            name: '-- Grafana --'
          group: grafana
          kind: DataQuery
          spec: {}
          version: v0
  cursorSync: 'Off'
  editable: true
  elements:
    panel-1:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    datasource:
                      name: efxdw7vo9jvnka
                    group: grafana-postgresql-datasource
                    kind: DataQuery
                    spec:
                      dataset: analytics
                      editorMode: code
                      format: table
                      rawQuery: true
                      rawSql: |-
                        SELECT
                            SUM(revenue) AS total_revenue
                        FROM sales;
                      sql:
                        columns:
                          - parameters: []
                            type: function
                        groupBy:
                          - property:
                              type: string
                            type: groupBy
                        limit: 50
                    version: v0
                  refId: A
            queryOptions: {}
            transformations: []
        description: ''
        id: 1
        links: []
        title: Total Revenue
        vizConfig:
          group: stat
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                color:
                  mode: thresholds
                thresholds:
                  mode: absolute
                  steps:
                    - color: green
                      value: 0
                    - color: red
                      value: 80
                unit: currencyGBP
              overrides: []
            options:
              colorMode: value
              graphMode: area
              justifyMode: auto
              orientation: auto
              percentChangeColorMode: standard
              reduceOptions:
                calcs:
                  - lastNotNull
                fields: ''
                values: false
              showPercentChange: false
              textMode: auto
              wideLayout: true
          version: 13.2.1
    panel-2:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    datasource:
                      name: efxdw7vo9jvnka
                    group: grafana-postgresql-datasource
                    kind: DataQuery
                    spec:
                      dataset: analytics
                      editorMode: code
                      format: table
                      rawQuery: true
                      rawSql: |-
                        SELECT
                            DATE_TRUNC('month', order_date) AS "time",
                            SUM(cost) AS cost,
                            SUM(revenue) AS revenue
                        FROM sales
                        GROUP BY 1
                        ORDER BY 1;
                      sql:
                        columns:
                          - parameters: []
                            type: function
                        groupBy:
                          - property:
                              type: string
                            type: groupBy
                        limit: 50
                    version: v0
                  refId: A
            queryOptions: {}
            transformations: []
        description: ''
        id: 2
        links: []
        title: Revenue & Cost Over Time
        vizConfig:
          group: timeseries
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                color:
                  mode: palette-classic
                custom:
                  axisBorderShow: false
                  axisCenteredZero: false
                  axisColorMode: text
                  axisLabel: ''
                  axisPlacement: auto
                  barAlignment: 0
                  barWidthFactor: 0.6
                  drawStyle: line
                  fillOpacity: 25
                  gradientMode: none
                  hideFrom:
                    legend: false
                    tooltip: false
                    viz: false
                  insertNulls: false
                  lineInterpolation: smooth
                  lineWidth: 1
                  pointSize: 5
                  scaleDistribution:
                    type: linear
                  showPoints: auto
                  showValues: false
                  spanNulls: false
                  stacking:
                    group: A
                    mode: none
                  thresholdsStyle:
                    mode: 'off'
                thresholds:
                  mode: absolute
                  steps:
                    - color: green
                      value: 0
                    - color: red
                      value: 80
                unit: currencyGBP
              overrides: []
            options:
              legend:
                calcs: []
                displayMode: list
                enableFacetedFilter: false
                placement: bottom
                showLegend: true
              tooltip:
                hideZeros: false
                mode: single
                sort: none
          version: 13.2.1
    panel-3:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    datasource:
                      name: efxdw7vo9jvnka
                    group: grafana-postgresql-datasource
                    kind: DataQuery
                    spec:
                      dataset: analytics
                      editorMode: code
                      format: table
                      rawQuery: true
                      rawSql: |-
                        SELECT
                            category,
                            SUM(revenue) AS revenue
                        FROM sales
                        GROUP BY category
                        ORDER BY revenue DESC;
                      sql:
                        columns:
                          - parameters: []
                            type: function
                        groupBy:
                          - property:
                              type: string
                            type: groupBy
                        limit: 50
                    version: v0
                  refId: A
            queryOptions: {}
            transformations: []
        description: ''
        id: 3
        links: []
        title: Revenue by Category
        vizConfig:
          group: piechart
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                color:
                  fixedColor: '#73BF69'
                  mode: palette-classic
                custom:
                  hideFrom:
                    legend: false
                    tooltip: false
                    viz: false
              overrides: []
            options:
              displayLabels:
                - percent
              legend:
                displayMode: list
                placement: bottom
                showLegend: true
              pieType: pie
              reduceOptions:
                calcs: []
                fields: ''
                values: true
              sort: desc
              tooltip:
                hideZeros: false
                mode: single
                sort: none
          version: 13.2.1
    panel-4:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    datasource:
                      name: efxdw7vo9jvnka
                    group: grafana-postgresql-datasource
                    kind: DataQuery
                    spec:
                      dataset: analytics
                      editorMode: code
                      format: table
                      rawQuery: true
                      rawSql: |-
                        SELECT
                            region,
                            SUM(revenue) AS revenue
                        FROM sales
                        GROUP BY region
                        ORDER BY revenue DESC;
                      sql:
                        columns:
                          - parameters: []
                            type: function
                        groupBy:
                          - property:
                              type: string
                            type: groupBy
                        limit: 50
                    version: v0
                  refId: A
            queryOptions: {}
            transformations: []
        description: ''
        id: 4
        links: []
        title: Revenue by Region
        vizConfig:
          group: barchart
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                color:
                  fixedColor: '#73BF69'
                  mode: palette-classic
                custom:
                  axisBorderShow: false
                  axisCenteredZero: false
                  axisColorMode: text
                  axisLabel: ''
                  axisPlacement: auto
                  fillOpacity: 80
                  gradientMode: none
                  hideFrom:
                    legend: false
                    tooltip: false
                    viz: false
                  lineWidth: 1
                  scaleDistribution:
                    type: linear
                  thresholdsStyle:
                    mode: 'off'
                thresholds:
                  mode: absolute
                  steps:
                    - color: green
                      value: 0
                    - color: red
                      value: 80
                unit: currencyGBP
              overrides: []
            options:
              barRadius: 0
              barWidth: 0.97
              fullHighlight: false
              groupWidth: 0.7
              legend:
                calcs: []
                displayMode: list
                placement: bottom
                showLegend: true
              orientation: auto
              showValue: auto
              stacking: none
              tooltip:
                hideZeros: false
                mode: single
                sort: none
              xTickLabelRotation: 0
              xTickLabelSpacing: 0
          version: 13.2.1
  layout:
    kind: GridLayout
    spec:
      items:
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-1
            height: 8
            width: 12
            x: 0
            'y': 0
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-2
            height: 8
            width: 12
            x: 12
            'y': 0
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-3
            height: 8
            width: 12
            x: 0
            'y': 8
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-4
            height: 8
            width: 12
            x: 12
            'y': 8
  links: []
  liveNow: false
  preferences:
    layout:
      kind: GridLayout
      spec:
        items: []
  preload: false
  tags: []
  timeSettings:
    autoRefresh: ''
    autoRefreshIntervals:
      - 5s
      - 10s
      - 30s
      - 1m
      - 5m
      - 15m
      - 30m
      - 1h
      - 2h
      - 1d
    fiscalYearStartMonth: 0
    from: '2024-01-01T00:00:00.000Z'
    hideTimepicker: false
    timezone: browser
    to: '2025-12-01T00:00:00.000Z'
  title: DX Analytics
  variables: []
